name: Build Mindustry iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 🔥 ВАЖНО: фиксируем Xcode 15 (RoboVM compatible)
      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Clone Arc backend
        run: git clone https://github.com/Anuken/Arc ../Arc

      - name: Give permissions to gradlew
        run: chmod +x gradlew

      - name: Build Mindustry iOS IPA
        run: ./gradlew ios:createIPA -PnoLocalArc=true

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mindustry-iOS
          path: ios/build/robovm/*.ipa
