name: Build Mindustry iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Clone Arc
        run: git clone https://github.com/Anuken/Arc ../Arc

      - name: Grant permissions
        run: chmod +x gradlew

      - name: Build iOS IPA
        run: |
          ./gradlew pack -PnoLocalArc=true
          ./gradlew :ios:deploy -Probovm.iosSkipSigning=true -PnoLocalArc=true

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Mindustry-iOS
          path: ios/build/robovm/*.ipa
